### ISSUE TITLE
ImportError: No module named os_client_config

### ISSUE THREAD

**Issue by gvenka008c** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#10]
Hi @lukaspustina 

I am getting the below error while executing the script. 

ERROR! The file inventory/openstack.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x inventory/openstack.py`.
Inventory script (inventory/openstack.py) had an execution error: Traceback (most recent call last):
  File "/var/lib/ansible/jenkins_mesos/ansible/inventory/openstack.py", line 54, in <module>
    import os_client_config
ImportError: No module named os_client_config

inventory/openstack.py:43: Expected key=value host variable assignment, got: argparse
# ansible --version

ansible 2.0.1.0

Please suggest. Thanks.

**Comment by lukaspustina** [comment]
Hi @gvenka008c,

I doubt that the particular file `inventory/openstack.py` is my script. First, I do not import `os_client_config` and second, line 43 is defining a map not importing anything. The former is why what your error message is saying failed. So there's little I can do.

Further, I never tested my script with Ansible 2+. I don't know if the format has been changed. But anyway that not the problem here.

Best regards,
Lukas

**Comment by shortsteps** [comment]
@gvenka008c , how did you solved?
I get the same error as yours running that openstack.py ( https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/openstack.py ) suggested in Ansible docs, not the Lukas one.

Thanks
